default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: <%= [5, *ENV.values_at("RAILS_MAX_THREADS", "SIDEKIQ_CONCURRENCY")].map(&:to_i).max %>

development:
  <<: *default
  database: kitchen_basics_development

test:
  <<: *default
  database: kitchen_basics_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
